name: Coverage actions
description: mono npm projects workflow, includes test and release.
author: DavidJones

inputs:
  codecov_token:
    description: 'Codecov Token'
    required: true
  artifact_name:
    description: 'The file name of artifacts'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    # 测试
    - name: Run tests and collect coverage
      shell: bash
      run: npm run ci:coverage
      env:
        # @see https://github.com/actions/runner-images/issues/70
        NODE_OPTIONS: '--max_old_space_size=4096'
    # 上传覆盖率
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ inputs.codecov_token }}
