name: Setup Node.js
description: Mono npm projects workflow, includes test and release.
author: DavidJones

inputs:
  node_version:
    description: 'Node Version'
    required: true
    default: '20'
  git_access_token:
    description: 'Git Access Token'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    # 拉取代码
    - name: Checkout project
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.git_access_token != '' && inputs.git_access_token || github.token }}
    # 配置 Git
    - name: Configure git authority
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    # 安装 Node
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
    # 启用 Corepack 并准备 pnpm (Node.js 20+ 内置支持)
    - name: Setup pnpm via Corepack
      shell: bash
      run: |
        corepack enable
        corepack prepare pnpm@10 --activate
    # 获取 store 目录并设置缓存路径
    - name: Get store directory
      id: pnpm-cache
      shell: bash
      run: |
        if command -v pnpm >/dev/null 2>&1 && (test -f "pnpm-lock.yaml" || find . -name "pnpm-lock.yaml" -type f | head -1 | grep -q .); then
          STORE_PATH=$(pnpm store path --silent)
          echo "STORE_PATH=$STORE_PATH" >> $GITHUB_ENV
          echo "path=$STORE_PATH" >> $GITHUB_OUTPUT
        else
          echo "STORE_PATH=node_modules" >> $GITHUB_ENV
          echo "path=node_modules" >> $GITHUB_OUTPUT
        fi
    # 缓存依赖
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.path }}
        key: ${{ runner.os }}-node-${{ inputs.node_version }}-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml', '**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node_version }}-
    # 安装依赖
    - name: Install dependencies
      shell: bash
      run: npx swpm install
