name: Setup actions
description: mono npm projects workflow, includes test and release.
author: DavidJones

inputs:
  node_version:
    description: 'Node Version'
    required: true
    default: '20'
  git_access_token:
    description: 'Git Access Token'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    # 拉取代码
    - name: Checkout project
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.git_access_token != '' && inputs.git_access_token || github.token }}
    # 配置 Git
    - name: Configure git authority
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    # 安装 Node
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
    # 安装 Pnpm
    - name: Install Pnpm
      uses: pnpm/action-setup@v4
      if: ${{ hashFiles('**/pnpm-lock.yaml') != '' }}
      with:
        version: 10
        run_install: false
    - name: Get store directory
      shell: bash
      run: |
        if [[ ${{ hashFiles('**/pnpm-lock.yaml') != '' }} ]]; then
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        else
          echo "STORE_PATH=**/node_modules/*" >> $GITHUB_ENV
        fi
    # 缓存依赖
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-node-${{ inputs.node_version }}-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml', '**/yarn.lock') }}
    # 安装依赖
    - name: Install dependencies
      shell: bash
      run: npx swpm install
