name: Github pages actions
description: deploy github page.
author: DavidJones

inputs:
  token:
    description: 'git auth token'
    required: true
  # 不传则下载而是掉多一次测试
  artifact_name:
    description: 'the file name of artifacts'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    # 下载覆盖率文件
    - name: download artifacts
      if: ${{ inputs.artifact_name != '' }}
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: success
        name: ${{ inputs.artifact_name }}
    # 生成覆盖率
    - name: Run tests and collect coverage
      if: ${{ inputs.artifact_name == '' }}
      uses: series-one/one-workflow/.github/actions/coverage-composite@main
    # 生成 gh-pages
    - name: build pages
      shell: bash
      run: yarn ci:pages
    # 发布 gh-pages
    - name: release to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.token }}
        publish_dir: ./gh-pages
