name: Github pages actions
description: deploy github page.
author: DavidJones

inputs:
  # Git access token，Github 生成
  token:
    description: 'Git Access Token'
    required: true
  # 不传则下载而是调多一次测试，有就下没有就不下
  # execute one more time coverage if empty
  artifact_name:
    description: 'The file name of artifacts'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    # 下载覆盖率文件
    - name: Download artifacts
      if: ${{ inputs.artifact_name != '' }}
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: success
        name: ${{ inputs.artifact_name }}
    # 生成覆盖率
    - name: Run tests and collect coverage
      if: ${{ inputs.artifact_name == '' }}
      uses: dumlj/dumlj-workflows/.github/actions/coverage-composite@main
    # 生成 gh-pages
    - name: Build github page source
      shell: bash
      run: yarn ci:pages
    # 发布 gh-pages
    - name: Release to github page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.token }}
        publish_dir: ./gh-pages
