name: gh-pages.workflow

on: [workflow_call]

env:
  # 默认分支
  CI_DEFAULT_BRANCH: main

jobs:
  # 发布 Github Pages
  pages:
    name: Page
    runs-on: macOS-latest
    steps:
      # 初始化
      - name: Initialize projects
        uses: dumlj/dumlj-workflows/.github/actions/setup-composite@main
        with:
          node_version: '20'
          git_access_token: ${{ secrets.CI_GIT_TOKEN }}
      # 发布 github apge
      - name: Deploy to github page
        uses: dumlj/dumlj-workflows/.github/actions/gh-pages-composite@main
        with:
          git_access_token: ${{ secrets.CI_GIT_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}